### ISSUE TITLE
Handle embedded pointers (crash)

### ISSUE THREAD

**Issue by klauspost** [pquerna/ffjson#112]
To reproduce:

``` Go
type XEmbedThis struct {
    S string
}
// Pointer to embedded type
type XEmbedPtr struct {
    *XEmbedThis `json:",omitempty"`
}
```

Marshalling an XEmbedPtr{} will result in a `panic: runtime error: invalid memory address or nil pointer dereference`.

This is the generated code:

``` Go
func (mj *XEmbedPtr) MarshalJSONBuf(buf fflib.EncodingBuffer) error {
    var err error
    var obj []byte
    _ = obj
    _ = err
    buf.WriteString(`{"S":`)
    fflib.WriteJsonString(buf, string(mj.S))
    buf.WriteByte('}')
    return nil
}
```

It should check if "mj.XEmbedThis" is nil before accessing mj.S. Not a trivial fix, I would expect.

**Comment by ugorji** [comment]
Bump

**Comment by erikdubbelboer** [comment]
I'm afraid this is not easy at all. The way the [parser works now](https://github.com/pquerna/ffjson/blob/9d7075fb37d35c5b005b4cd3bdd1074e345a5d4e/inception/reflect.go#L217-L224) it looses all information about the anonymous struct. Adding this information is not easy at all and gets quite complicated when supporting multiple layers of embedded structs. I guess the easiest way is to treat an embedded struct as a separate struct and call the marshaller/unmarshaller for this struct instead of embedding its members. This would result in slightly slower code I'm afraid.
