### ISSUE TITLE
ffjson 2x slower for unmarshal than encoding/json

### ISSUE THREAD

**Issue by iand** [pquerna/ffjson#125]
I'm experimenting with ffjson for a struct we use very heavily in our advertising platform. I was surprised to get a 2x slowdown in unmarshal performance when compared to encoding/json:

```
BenchmarkUnmarshalRequestStdlib	   20000	     68320 ns/op	    5953 B/op	     142 allocs/op
BenchmarkUnmarshalRequestFfjson	   10000	    119168 ns/op	   17420 B/op	     376 allocs/op
```
I think I am using ffjson correctly, but perhaps I've made a mistake

However, it may be that struct I'm unmarshalling is not a good fit for ffjson and so it might be of interest to the authors. The struct is quite complex with several sub structs, but it's main feature is that nearly every field is optional and is expressed as a pointer. 

Benchmark code is here https://github.com/avct/openrtb/blob/ffjson/benchmark_test.go (ffjson branch of https://github.com/avct/openrtb). Struct being unmarshalled is at https://github.com/avct/openrtb/blob/ffjson/request.go

**Comment by klauspost** [comment]
Looking at https://github.com/avct/openrtb/blob/ffjson/request_ffjson.go - it seems a lot are falling back to json.Unmarshal

If you added ffjson files for `openrtb.Impression`,`openrtb.Site`, `openrtb.App`, `openrtb.Device`, `openrtb.User`, `openrtb.Regulations`,`openrtb.Extensions` and `openrtb.Pmp` types, ffjson will be able to encode these fields directly, and not have to go through the json library.

@pquerna: I don't know much about the decoder, maybe you have something to add.

**Comment by sigmonsays** [comment]
i'm  seeing 2x penalty slow down as well for decoding. decoding a million records takes 1m8s without ffjson and 2m34s. 

Looking at a cpu profile (smaller set 100k) it looks like most time is spent in fflib. I believe scanblock is from excessive garbage generation.
<pre>
(pprof) top10
7660ms of 15740ms total (48.67%)
Dropped 105 nodes (cum <= 78.70ms)
Showing top 10 nodes out of 94 (cum >= 350ms)
      flat  flat%   sum%        cum   cum%
    2290ms 14.55% 14.55%     2290ms 14.55%  scanblock
    1060ms  6.73% 21.28%     1110ms  7.05%  encoding/json.stateInString
     980ms  6.23% 27.51%     1340ms  8.51%  runtime.mallocgc
     640ms  4.07% 31.58%     1350ms  8.58%  encoding/json.(*Decoder).readValue
     600ms  3.81% 35.39%     1730ms 10.99%  encoding/json.nextValue
     490ms  3.11% 38.50%      490ms  3.11%  runtime.memmove
     470ms  2.99% 41.49%     1080ms  6.86%  encoding/json.checkValid
     400ms  2.54% 44.03%      400ms  2.54%  runtime.MSpan_Sweep
     380ms  2.41% 46.44%     5320ms 33.80%  github.com/pquerna/ffjson/fflib/v1.(*FFLexer).Scan
     350ms  2.22% 48.67%      350ms  2.22%  github.com/pquerna/ffjson/fflib/v1.scanString
</pre>

**Comment by pquerna** [comment]
most of these slowdowns are due to when we fallback on the decoder, we have to scan out the whole sub-field in the JSON, and then copy it over to the `encoding/json` decoder, which does its own scan of the JSON.

I'll try to dive into @iand's case today though, should be doing better for sure.

**Comment by klauspost** [comment]
Maybe we should have a look at possibly inlining "foreign" structs like the encoder does with anonymous members.

**Comment by iand** [comment]
Thanks for taking a look at this. @klauspost I tried your suggestion and generated ffjson unmarshallers for all structs in the package. Unfortunately the benchmarks are worse so there's clearly something quite strange going on.

BenchmarkUnmarshalRequest	   10000	    150823 ns/op	   23196 B/op	     482 allocs/op

Same benchmark as before but in a new `ffjson-all` branch: https://github.com/avct/openrtb/blob/ffjson-all/benchmark_test.go

**Comment by pquerna** [comment]
Yeah, the allocs-per-operation are crazy high.

**Comment by klauspost** [comment]
I had a short look. These things stand out so far:

# 1 - Bug in unmarshalFasterType
First of all, a bug: The `unmarshalFasterType` is not detected, since `handleFieldAddr` should test a pointer to the type, and not the type itself. This works:
```
func handleFieldAddr(ic *Inception, name string, takeAddr bool, typ reflect.Type, ptr bool) string {
	out := ""
	out += fmt.Sprintf("/* handler: %s type=%v kind=%v */\n", name, typ, typ.Kind())

	// typ changed to reflect.PtrTo(typ) here:
	umlx := reflect.PtrTo(typ).Implements(unmarshalFasterType) || typeInInception(ic, typ, shared.MustDecoder)
[...]
```
This change cuts allocations in half, and brings performance close to encoding/json.

# 2 Slice decoding
Slices are falling back to "json.Unmarshal". The `Request` has 5 slices, and all of them have the field captured and Unmarshalled. This is an obvious place to optimize.

# 3 Lexer -> WriteJsonString
When the lexer calls WriteJsonString can be made leaner:

This was mainly a hotspot because of the issues above, but getting a string from the capture buffer and sending it to `WriteJsonString` caused many allocations. I tried sending a buffer instead, and it shaved of a few allocations. Something like:
```Go
// Function to keep compatibility
func WriteJsonString(buf JsonStringWriter, s string) {
	WriteJsonStringB(buf,[]byte(s))
}

/**
 * Function ported from encoding/json: func (e *encodeState) string(s string) (int, error)
 */
func WriteJsonStringB(buf JsonStringWriter, s []byte) {

// (exchange buf.WriteString(s[start:i]) -> buf.Write(s[start:i]))
```
The Lexer has two calls to `WriteJsonString`, and they can be adjusted easily to send a buffer.


# 4 Scratch buffer
There are a few places where a `var buf Buffer` is used. If you put that as a member of the Lexer, so it can be re-used.

# 5 Re-encoding strings when capturing?

It seems strange to decode and afterwards encode json strings when capturing. Surely there must be a way to just copy the original.


# @iand: Use ffjson.Unmarshal

As per the readme, use the ffjson library for your Unmarshal calls. That will also help. Compare:
```Go
import "github.com/pquerna/ffjson/ffjson"

func BenchmarkUnmarshalRequestFF(b *testing.B) {
	for i := 0; i < b.N; i++ {
		req := &Request{}
		ffjson.Unmarshal(requests[i%len(requests)], req)
	}
}
```

I have quickly hacked together 1, 3 and 4, which gives me:
```
FFJSON: 20000             64353 ns/op            6702 B/op        143 allocs/op
JSON:   20000             74354 ns/op            5288B/op        142 allocs/op
```

Fallbacks to json.Unmarshal (probably because of 2) is responsible for about half the allocations, so if we can handle slices of structs without falling back we should have a significant edge.

**Comment by klauspost** [comment]
Added PR #126 (fixes issue 1) and PR #127 (fixes 3 +4)

**Comment by klauspost** [comment]
Added PR #128 (fixes 2)

**Comment by klauspost** [comment]
The fixes have landed. Your benchmark now looks like this:
```
ffjson:
BenchmarkUnmarshalRequestFF        30000             45569 ns/op            5721 B/op        123 allocs/op

No ffjson:
BenchmarkUnmarshalRequestFF        20000             76204 ns/op            5288 B/op        142 allocs/op
```
Now `ffjson` takes ~59% of the time of encoding/json.

There are fallbacks in case there are "Extensions" because they are map[string]interface{}, but fixing them will be a longer process. There are also fallback for "Publisher"/"Producer" types since they are aliases, which currently isn't resolved.

The benchmark looks like this:
```Go 
func BenchmarkUnmarshalRequestFF(b *testing.B) {
	for i := 0; i < b.N; i++ {
		req := &Request{}
		ffjson.Unmarshal(requests[i%len(requests)], req)
	}
}
```

**Comment by iand** [comment]
Excellent, thank you for your work on this. Here are my benchmarks for comparison. You can see they are similar to yours and show a good speedup over just using vanilla encoding/json

Using ffjson generated unmarshalling code with encoding/json Unmarshal function:
```
BenchmarkUnmarshalRequest  	   20000	     62721 ns/op	    6597 B/op	     132 allocs/op
```

Using ffjson generated unmarshalling code with ffjson Unmarshal function:
```
BenchmarkUnmarshalRequestFF	   30000	     44494 ns/op	    6101 B/op	     123 allocs/op
```
Feel free to close this issue and thanks again.

**Comment by klauspost** [comment]
Found a final optimization, in PR #131, which eliminates fallback for  "Publisher"/"Producer". Times are now:
```
BenchmarkUnmarshalRequestFF        30000             41802 ns/op            5477 B/op        121 allocs/op
```
Shaving off another 5%.
