### ISSUE TITLE
Probable Unicode conversion

### ISSUE THREAD

**Issue by rbkumar88** [pquerna/ffjson#252]
Is this behaviour expected? If so how to negate that.

```package main

import (
	"fmt"
	"github.com/pquerna/ffjson/ffjson"
)

func main() {
	level:=&Level{Label:"<<< GET"}
	testFfjson(level)
}
type Level struct {
	Label      string
}
func testFfjson(m interface{}) {
	b,err:= ffjson.Marshal(&m)
	if err!=nil{
		fmt.Printf("error in ffjson marshal for %v : %v",m,err)
		return 
	}
	fmt.Printf("%s\n", b)
}
```

Output:

```{"Label":"\u003c\u003c\u003c GET"}```

**Comment by erikdubbelboer** [comment]
Yes this is expected. This is exactly the same as with the `encoding/json` package: https://play.golang.org/p/IHXPJmjh_bM
Both packages do this because it's perfectly valid JSON and JSON is mostly used inside a web context where `<` might cause issues with HTML tags.

And just like with `encoding/json` you can use the `Encoder.SetEscapeHTML(false)` to turn this off: https://play.golang.org/p/1sGNH1ae6zm

**Comment by pquerna** [comment]
@erikdubbelboer Thank you for explaining!
